language: node_js
node_js:
  12.6.0
install: npm install
script: gatsby build
deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: gatsby-blog-test
  skip_cleanup: true
  acl: public_read
  local_dir: public